"""Compare IDP extraction against MuleSoft data from Salesforce.

Produces a list of structured Findings + a confidence score for the case.
Pure logic — no Salesforce calls, no I/O. Takes two dicts in, returns a result.
"""
import logging
import re
from dataclasses import dataclass, field
from difflib import SequenceMatcher
from typing import Any

logger = logging.getLogger(__name__)


# Finding categories
DUPLICATE_MEMBER = "DUPLICATE_MEMBER"
DUPLICATE_INCOME = "DUPLICATE_INCOME"
DUPLICATE_ASSET = "DUPLICATE_ASSET"
MISSING_MEMBER = "MISSING_MEMBER"     # AI found, MuleSoft missed
MISSING_INCOME = "MISSING_INCOME"     # AI found, MuleSoft missed
MISSING_ASSET = "MISSING_ASSET"       # AI found, MuleSoft missed
IDP_MISSED_MEMBER = "IDP_MISSED_MEMBER"   # MuleSoft has, AI missed
IDP_MISSED_INCOME = "IDP_MISSED_INCOME"
IDP_MISSED_ASSET = "IDP_MISSED_ASSET"
VALUE_MISMATCH = "VALUE_MISMATCH"
COMPLIANCE = "COMPLIANCE"
# IDP-internal findings (not from comparison) — generated by the pipeline
# from cross-doc validation, special scenarios, bug detection, cert type
# rules, and field-level scoring.
INTERNAL_DISCREPANCY = "INTERNAL_DISCREPANCY"  # income/asset mismatches within the file
FIELD_QUALITY = "FIELD_QUALITY"                # [RED]/[YELLOW] field-level scoring findings
EXTRACTION_NOTE = "EXTRACTION_NOTE"            # workflow notes (pages excluded, name variants)


@dataclass
class Finding:
    category: str
    severity: str    # "high" | "medium" | "low" | "info"
    message: str
    detail: dict[str, Any] = field(default_factory=dict)


@dataclass
class Confidence:
    extraction_score: float
    agreement_rate: float
    case_confidence: float
    flag: str    # "green" | "yellow" | "red"
    agreements: int
    disagreements: int
    ai_only_records: int
    sf_only_records: int


@dataclass
class ComparisonResult:
    findings: list[Finding]
    confidence: Confidence


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ssn_last4(ssn: str | None) -> str:
    if not ssn:
        return ""
    return str(ssn).replace("-", "").replace("*", "")[-4:]


def _norm(s: str | None) -> str:
    return (s or "").strip().lower()


def _money(v: Any) -> float | None:
    if v is None or v == "":
        return None
    try:
        return float(str(v).replace(",", "").replace("$", "").strip())
    except (ValueError, TypeError):
        return None


def _close(a: float, b: float, tolerance: float = 0.05) -> bool:
    if a == 0 and b == 0:
        return True
    if a == 0 or b == 0:
        return False
    return abs(a - b) / max(abs(a), abs(b)) < tolerance


# Policy thresholds for escalating a dollar-amount mismatch to CRITICAL.
# These are POLICY defaults, not values derived from any single sample — tune
# against real audit volume. Both gates must hold so a modest percentage on a
# big number AND a big percentage on a trivial number both stay REVIEW.
_MISMATCH_REL_GAP = 0.25       # relative gap (|a-b| / larger) at/above this, AND
_MISMATCH_ABS_GAP = 1000.0     # absolute gap (dollars) at/above this -> CRITICAL


def _value_mismatch_severity(
    a: float, b: float,
    *, rel_high: float = _MISMATCH_REL_GAP, abs_high: float = _MISMATCH_ABS_GAP,
) -> str:
    """Severity for a dollar-amount mismatch, escalated by magnitude.

    A large gap on a material amount is CRITICAL ("high"); everything else is
    "medium". e.g. $2,380 vs $55,884 (96%, $53k) -> high; $172 vs $272
    (37%, $99) -> medium. Thresholds are module-level policy (see above).
    """
    hi = max(abs(a), abs(b))
    if hi <= 0:
        return "medium"
    rel = abs(a - b) / hi
    if rel >= rel_high and abs(a - b) >= abs_high:
        return "high"
    return "medium"


# ---------------------------------------------------------------------------
# Synonym tables — map AI extraction names to MuleSoft's abbreviations.
# Both sides get normalized to a canonical form before comparison.
# Maps to either an explicit canonical or a longer matching string.
# ---------------------------------------------------------------------------

_INCOME_SOURCE_SYNONYMS: dict[str, str] = {
    # Social Security family
    "ssa": "social security administration",
    "ss": "social security administration",
    "social security": "social security administration",
    "social security administration": "social security administration",
    # SSI
    "ssi": "supplemental security income",
    "supplemental security income": "supplemental security income",
    # SSDI
    "ssdi": "social security disability",
    "social security disability": "social security disability",
    # State supplements (varies by state — group together)
    "ssp": "state supplement program",
    "state supplement program": "state supplement program",
    "massachusetts state supplement program": "state supplement program",
    "ma ssp": "state supplement program",
    "ma state supplement": "state supplement program",
    # Public assistance
    "tanf": "temporary assistance",
    "temporary assistance": "temporary assistance",
    "calworks": "temporary assistance",
    "colorado works program": "temporary assistance",
    "colorado works": "temporary assistance",
    "afdc": "temporary assistance",
    # Anticipated income — MuleSoft sometimes uses this as a generic
    # bucket; treat as "self-declared" so it can match AI's TIC extraction.
    "anticipated income": "self-declared",
    "self-declared": "self-declared",
    "self declared": "self-declared",
}


def _normalize_income_source(name: str | None) -> str:
    """Map an income source name to its canonical form for comparison."""
    raw = _norm(name)
    if not raw:
        return ""
    if raw in _INCOME_SOURCE_SYNONYMS:
        return _INCOME_SOURCE_SYNONYMS[raw]
    # Word-boundary fallback — handle "Massachusetts SSP", "MA SSI", etc.
    # A single-word synonym must match a WHOLE token (never an arbitrary
    # substring — otherwise 'ss' inside 'ssi' would wrongly map SSI → Social
    # Security). A multi-word synonym must appear as a contiguous phrase.
    # Longest synonyms first so the most specific one wins.
    raw_tokens = {t for t in re.split(r"[^a-z0-9]+", raw) if t}
    for synonym in sorted(_INCOME_SOURCE_SYNONYMS, key=len, reverse=True):
        syn_tokens = [t for t in re.split(r"[^a-z0-9]+", synonym) if t]
        if len(syn_tokens) == 1:
            if syn_tokens[0] in raw_tokens:
                return _INCOME_SOURCE_SYNONYMS[synonym]
        elif synonym in raw:
            return _INCOME_SOURCE_SYNONYMS[synonym]
    return raw


# Common organizational suffixes/prefixes — stripped before fuzzy matching
# so "Coherent Corp" matches "Coherent", "The Walt Disney Company" matches
# "Walt Disney Company", etc.
_ORG_SUFFIXES = {
    "corp", "corporation", "inc", "incorporated", "llc", "l.l.c",
    "ltd", "limited", "co", "company", "lp", "l.p", "llp",
    "plc", "pllc", "pc", "p.c", "group", "holdings",
}
_ORG_PREFIXES = {"the", "a", "an"}


def _normalize_org_name(name: str | None) -> str:
    """Strip common corporate suffixes/prefixes for fuzzy comparison.

    Examples:
      'Coherent Corp'             → 'coherent'
      'The Walt Disney Company'   → 'walt disney'
      'B&T Building Services Inc' → 'b&t building services'
      'XYZ, LLC.'                 → 'xyz'
    """
    raw = _norm(name)
    if not raw:
        return ""
    # Strip punctuation that commonly appears in business names.
    # Slash/ampersand/hyphen are token separators ("Aarp/New York Life" should
    # tokenize as ["aarp", "new", "york", "life"], not keep "aarp/new" joined),
    # so they become spaces. Apostrophes are removed (don't → dont, one token).
    cleaned = re.sub(r"[,./&\-]", " ", raw).replace("'", "")
    tokens = [t for t in cleaned.split() if t]
    # Drop trailing org suffixes
    while tokens and tokens[-1] in _ORG_SUFFIXES:
        tokens.pop()
    # Drop leading articles
    while tokens and tokens[0] in _ORG_PREFIXES:
        tokens.pop(0)
    return " ".join(tokens) if tokens else raw


def _name_similarity(a: str, b: str) -> float:
    """Best-of full-string and token-coverage similarity.

    Full-string ratio handles "Walt Disney Company" vs "The Walt Disney
    Company" cleanly. But OCR errors like "chilts" vs "chilis bar & grill"
    fail the full-string check (extra tokens drag the ratio down).

    The token score averages each token's best match across the other
    name's tokens (over the shorter token list). A single shared surname
    or generic word ("Ana Lopez" vs "Carlos Lopez", "ABC Staffing" vs
    "XYZ Staffing") is diluted by the non-matching tokens instead of
    scoring the whole pair 1.0 — while a lone OCR-mangled token still
    scores on its best pair.
    """
    if not a or not b:
        return 0.0
    full_ratio = SequenceMatcher(None, a, b).ratio()

    a_tokens = [t for t in a.split() if len(t) > 2]
    b_tokens = [t for t in b.split() if len(t) > 2]
    token_score = 0.0
    if a_tokens and b_tokens:
        short, long_ = (
            (a_tokens, b_tokens) if len(a_tokens) <= len(b_tokens)
            else (b_tokens, a_tokens)
        )
        best_ratios = [
            max(SequenceMatcher(None, ts, tl).ratio() for tl in long_)
            for ts in short
        ]
        token_score = sum(best_ratios) / len(best_ratios)

    return max(full_ratio, token_score)


def _normalize_account_type(t: str | None) -> str:
    """Strip variants of 'Account' suffix so 'Checking' matches 'Checking Account'.

    Also collapses some common synonyms:
      'investment account', 'stocks', 'brokerage' → 'investment'
      '401k', 'ira', 'retirement account'         → 'retirement'
    """
    raw = _norm(t)
    if not raw:
        return ""
    # Strip trailing " account" / " acct" / leading "personal "
    for suffix in (" account", " acct", " accts"):
        if raw.endswith(suffix):
            raw = raw[: -len(suffix)].strip()
    if raw.startswith("personal "):
        raw = raw[len("personal "):].strip()
    # Common synonyms
    synonyms = {
        "stocks": "investment",
        "brokerage": "investment",
        "investment account": "investment",
        "401k": "retirement",
        "ira": "retirement",
        "roth ira": "retirement",
        "money market": "savings",
        "cd": "savings",
        "certificate of deposit": "savings",
    }
    return synonyms.get(raw, raw)


def _account_types_compatible(a: str | None, b: str | None) -> bool:
    """Loose accountType match — allows 'Checking' ≈ 'Checking Account'."""
    na = _normalize_account_type(a)
    nb = _normalize_account_type(b)
    if not na or not nb:
        return True   # one side missing — don't block on type
    return na == nb


# ---------------------------------------------------------------------------
# Cluster helpers — collapse variant spellings into one finding so analysts
# don't see "AI missed walmart" + "AI missed wal-mart" + "AI missed walmart inc"
# as three findings when MuleSoft is just storing the same employer 3 ways.
# ---------------------------------------------------------------------------

def _cluster_income_keys(
    keys: set[tuple[str, str]],
    threshold: float = 0.85,
) -> list[list[tuple[str, str]]]:
    """Group (source, member) tuples whose source names are near-identical
    after org-name normalization. Same member required to cluster — different
    members keep their findings separate.
    Empty source names are dropped (they produce useless findings).
    """
    clusters: list[list[tuple[str, str]]] = []
    for k in keys:
        if not k[0]:
            continue
        norm = _normalize_org_name(k[0])
        attached = False
        for cluster in clusters:
            rep = cluster[0]
            if rep[1] != k[1]:
                continue
            if _name_similarity(norm, _normalize_org_name(rep[0])) >= threshold:
                cluster.append(k)
                attached = True
                break
        if not attached:
            clusters.append([k])
    return clusters


def _cluster_asset_keys(
    keys: set[tuple[str, str, str]],
    threshold: float = 0.85,
) -> list[list[tuple[str, str, str]]]:
    """Group asset keys that look like the same real-world account.

    Two keys cluster when accountTypes are compatible AND either:
      - both have a real (non-stub) last4 that matches, OR
      - source names fuzzy-match after org-name normalization.
    Keys with no source AND no real last4 are dropped.
    """
    clusters: list[list[tuple[str, str, str]]] = []
    for k in keys:
        src, atype, last4 = k
        is_stub = (not last4) or last4.startswith("~")
        if not src and is_stub:
            continue
        attached = False
        for cluster in clusters:
            rep_src, rep_type, rep_last4 = cluster[0]
            if not _account_types_compatible(atype, rep_type):
                continue
            rep_stub = (not rep_last4) or rep_last4.startswith("~")
            # Strong: matching real account numbers
            if not is_stub and not rep_stub and last4 == rep_last4:
                cluster.append(k)
                attached = True
                break
            # Fall back to source-name similarity
            if src and rep_src:
                if _name_similarity(
                    _normalize_org_name(src),
                    _normalize_org_name(rep_src),
                ) >= threshold:
                    cluster.append(k)
                    attached = True
                    break
        if not attached:
            clusters.append([k])
    return clusters


# ---------------------------------------------------------------------------
# Member comparison
# ---------------------------------------------------------------------------

def _member_key(rec: dict) -> tuple[str, str]:
    """Strict identity key: (DOB, last 4 of SSN)."""
    dob = rec.get("DOB") or rec.get("DOB__c") or ""
    # Salesforce sometimes returns dates as ISO datetime strings; normalize to date-only.
    dob_str = str(dob)[:10] if dob else ""
    return (
        dob_str,
        _ssn_last4(rec.get("socialSecurityNumber") or rec.get("SSN__c")),
    )


def _member_name_key(rec: dict) -> str:
    """Fallback key based on name — used when DOB/SSN are partial."""
    first = (rec.get("FirstName") or rec.get("First_Name__c") or "").strip().lower()
    last = (rec.get("LastName") or rec.get("Last_Name__c") or "").strip().lower()
    return f"{first} {last}".strip()



def _display_name(rec: dict, first_key: str = "FirstName", last_key: str = "LastName") -> str:
    """Join name parts, skipping None/empty — a partial record must render
    'Pictrantonio', not 'None Pictrantonio'."""
    return " ".join(
        str(p) for p in (rec.get(first_key), rec.get(last_key)) if p
    ) or "(unknown)"


def _compare_members(
    ai_members: list[dict], sf_members: list[dict], *, ir_scoped: bool = False,
) -> tuple[list[Finding], dict]:
    findings: list[Finding] = []

    # SF dedup: warn on duplicates within SF
    sf_keys: dict[tuple, list[dict]] = {}
    for m in sf_members:
        k = _member_key(m)
        sf_keys.setdefault(k, []).append(m)

    for k, group in sf_keys.items():
        if len(group) > 1 and k != ("", ""):
            name = _display_name(group[0], "First_Name__c", "Last_Name__c")
            findings.append(Finding(
                category=DUPLICATE_MEMBER,
                severity="high",
                message=f"DUPLICATE MEMBER — {name} appears {len(group)} times in MuleSoft",
                detail={"key": list(k), "count": len(group)},
            ))

    ai_keys: dict[tuple[str, str], dict] = {}
    for i, m in enumerate(ai_members):
        k = _member_key(m)
        if k == ("", ""):
            # No DOB/SSN extracted. A named member must still reach the
            # name-based fuzzy fallback below — dropping them here turns
            # every OCR-degraded packet into a false "AI missed member" +
            # a silently vanished AI member. The synthetic key keeps
            # multiple no-identity members distinct and can never collide
            # with a real SF key, so strict matching is unaffected.
            if not _member_name_key(m):
                continue    # neither identity nor name — nothing to match on
            k = ("", f"~noid{i}")
        ai_keys[k] = m
    sf_keys_set = {k for k in sf_keys if k != ("", "")}

    matched = ai_keys.keys() & sf_keys_set
    ai_only_keys = ai_keys.keys() - sf_keys_set
    sf_only_keys = sf_keys_set - ai_keys.keys()

    # Name-based fuzzy fallback: if a member's strict (DOB, SSN) key
    # doesn't match across systems but their NAMES are similar (e.g.,
    # "Yvet Belen" vs "Yvett Belen" — single-letter OCR variant), treat
    # as matched and surface a low-severity mismatch finding instead of
    # flagging both directions as missing.
    ai_only_with_names = [
        (_member_name_key(ai_keys[k]), k) for k in ai_only_keys
    ]
    sf_only_with_names = [
        (_member_name_key(sf_keys[k][0]), k) for k in sf_only_keys
    ]

    fallback_matched_ai_keys: set[tuple[str, str]] = set()
    fallback_matched_sf_keys: set[tuple[str, str]] = set()
    fuzzy_match_pairs: list[tuple[str, str]] = []

    for ai_name, ai_k in ai_only_with_names:
        if not ai_name:
            continue
        best_ratio = 0.0
        best_sf_key: tuple[str, str] | None = None
        best_sf_name: str = ""
        for sf_name, sf_k in sf_only_with_names:
            if not sf_name or sf_k in fallback_matched_sf_keys:
                continue
            # 0.82 threshold catches single-letter OCR variants like
            # "Latisha" / "Latticia" (ratio 0.83) and "Yvet" / "Yvett"
            # (ratio 0.95). Tighter would miss those; looser risks
            # false-matching distinct names.
            ratio = _name_similarity(ai_name, sf_name)
            if ratio > best_ratio:
                best_ratio = ratio
                best_sf_key = sf_k
                best_sf_name = sf_name
        if best_ratio >= 0.82 and best_sf_key is not None:
            fallback_matched_ai_keys.add(ai_k)
            fallback_matched_sf_keys.add(best_sf_key)
            fuzzy_match_pairs.append((ai_name, best_sf_name))

    ai_only = ai_only_keys - fallback_matched_ai_keys
    sf_only = sf_only_keys - fallback_matched_sf_keys

    # Surface the fuzzy matches as a single low-severity finding per pair
    for ai_name, sf_name in fuzzy_match_pairs:
        if ai_name == sf_name:
            msg = (
                f"Member identity mismatch — '{ai_name.title()}' exists in "
                f"both systems but DOB/SSN keys differ"
            )
        else:
            msg = (
                f"Name spelling variant — AI: '{ai_name.title()}' vs "
                f"MuleSoft: '{sf_name.title()}' (likely same person)"
            )
        findings.append(Finding(
            category=VALUE_MISMATCH,
            severity="low",
            message=msg,
        ))

    for k in ai_only:
        m = ai_keys[k]
        name = _display_name(m)
        ssn4 = k[1] if not str(k[1]).startswith("~noid") else None
        findings.append(Finding(
            category=MISSING_MEMBER,
            severity="high",
            message=(
                f"MuleSoft missing household member — {name} "
                f"(DOB: {m.get('DOB')}, "
                f"SSN: {'***-**-' + ssn4 if ssn4 else 'not extracted'})"
            ),
            detail={"name": name, "dob": m.get("DOB"), "ssn4": ssn4},
        ))

    for k in sf_only:
        m = sf_keys[k][0]
        name = _display_name(m, "First_Name__c", "Last_Name__c")
        if ir_scoped:
            sev, msg = "info", (
                f"{name} is in MuleSoft's full-case record but not the interim "
                f"packet — verify if changed (IR)"
            )
        else:
            sev, msg = "medium", (
                f"AI may have missed household member — {name} "
                f"is in MuleSoft but not in AI extraction"
            )
        findings.append(Finding(
            category=IDP_MISSED_MEMBER,
            severity=sev,
            message=msg,
            detail={"name": name, "ssn4": k[1]},
        ))

    # Value mismatch on matched members (Disabled / Head)
    for k in matched:
        ai_m = ai_keys[k]
        sf_m = sf_keys[k][0]
        ai_dis = _norm(ai_m.get("disabled"))
        sf_dis = "y" if sf_m.get("Disabled__c") else "n" if sf_m.get("Disabled__c") is False else ""
        if ai_dis and sf_dis and ai_dis != sf_dis:
            findings.append(Finding(
                category=VALUE_MISMATCH,
                severity="medium",
                message=(
                    f"Disability mismatch — {_display_name(ai_m)}: "
                    f"AI={ai_dis} MuleSoft={sf_dis}"
                ),
            ))

        # Head-of-household disagreement. IDP marks head with "H"; MuleSoft
        # uses a boolean Head__c. The two systems disagreeing on who heads the
        # household is worth surfacing (it shifts income/asset attribution and
        # which member the cert is built around). Only flag when MuleSoft has a
        # definite value.
        ai_head = "y" if _norm(ai_m.get("head")) in ("h", "y", "head", "1", "true") else "n"
        sf_head_raw = sf_m.get("Head__c")
        sf_head = "y" if sf_head_raw else "n" if sf_head_raw is False else ""
        if sf_head and ai_head != sf_head:
            findings.append(Finding(
                category=VALUE_MISMATCH,
                severity="medium",
                message=(
                    f"Head-of-household mismatch — {_display_name(ai_m)}: "
                    f"AI={'head' if ai_head == 'y' else 'not head'} "
                    f"MuleSoft={'head' if sf_head == 'y' else 'not head'}"
                ),
            ))

    return findings, {
        "agreements": len(matched),
        "disagreements": 0,
        "ai_only": len(ai_only),
        "sf_only": len(sf_only),
    }


# ---------------------------------------------------------------------------
# Income comparison
# ---------------------------------------------------------------------------

# Canonical benefit programs (values of _INCOME_SOURCE_SYNONYMS) for which
# the PROGRAM is the income's identity, not the payer. SSA pays both
# retirement Social Security and SSI — keying those by payer collides two
# distinct benefits for the same member into one key, so one amount
# silently overwrites the other and the comparison diffs mismatched pairs.
_BENEFIT_PROGRAM_KEYS = frozenset({
    "social security administration",
    "supplemental security income",
    "social security disability",
    "state supplement program",
    "temporary assistance",
})

# SSA-family programs: one system often records a program-specific
# benefit (SSDI, SSI) under the generic payer ("Social Security"), so
# generic↔specific pairs within this family are amount-matchable — the
# program keys differ but member + annual amount agreement means it's
# the same income.
_SSA_FAMILY = frozenset({
    "social security administration",
    "social security disability",
    "supplemental security income",
    "state supplement program",
})

# Generic bucket names one system uses when the payer's actual name wasn't
# captured. These never anchor missing/missed findings on their own — a
# record keyed to a placeholder is matched by income type + member instead.
_PLACEHOLDER_INCOME_SOURCES = frozenset({
    "other non wage source",
    "other non-wage source",
    "other income",
    "other",
    "anticipated income",
    "non wage source",
})


def _income_sources_compatible(a: str, b: str) -> bool:
    """Same canonical source, or generic↔specific within the SSA family."""
    if a == b:
        return True
    return a in _SSA_FAMILY and b in _SSA_FAMILY


def _income_key(rec: dict) -> tuple[str, str]:
    """Benefit program (for government benefits) or source name + member.

    AI extracts full names ('social security administration'), MuleSoft
    often uses abbreviations ('ssa'). Both go through the same synonym
    map so they match correctly. For benefit income the normalized
    income TYPE is the identity — see _BENEFIT_PROGRAM_KEYS.
    """
    source = rec.get("sourceName") or rec.get("Source_Name__c")
    income_type = rec.get("incomeType") or rec.get("Income_Type__c")
    member = rec.get("memberName") or rec.get("House_Member_Name__c") or ""
    # Normalize member: trim middle initial / 'r.' / 'jr' suffixes for fuzzy match.
    member_clean = _norm(member).replace(".", "").strip()
    member_tokens = [t for t in member_clean.split() if len(t) > 1]
    if len(member_tokens) >= 2:
        # First + last token only: middle names appear inconsistently
        # across records ('Dana Gann' on the VOI, 'Dana Kay Gann' on the
        # benefit letter) and would split one member's income across
        # unjoinable keys.
        member_key = f"{member_tokens[0]} {member_tokens[-1]}"
    else:
        member_key = " ".join(member_tokens) if member_tokens else member_clean

    type_norm = _normalize_income_source(income_type)
    if type_norm in _BENEFIT_PROGRAM_KEYS:
        return (type_norm, member_key)
    return (_normalize_income_source(source), member_key)


def _sf_group_amount(group: list[dict]) -> float | None:
    """Comparable annual amount for MuleSoft rows sharing one income key.

    Distinct amounts are separate payments of the same benefit — sum them.
    Identical amounts are duplicate rows — count once (the duplicate is
    flagged separately; double-counting it would manufacture a mismatch).
    """
    amounts = [
        a for a in (_money(r.get("Gross_Member_Income__c")) for r in group)
        if a is not None
    ]
    if not amounts:
        return None
    if len({round(a, 2) for a in amounts}) == 1:
        return amounts[0]
    return sum(amounts)


def _compare_income(
    ai_income: list[dict], ai_calculations: list[dict], sf_income: list[dict],
    *, ir_scoped: bool = False,
) -> tuple[list[Finding], dict]:
    findings: list[Finding] = []

    # Build map of AI annual amounts by source. Use _income_key so the
    # keys go through the same synonym normalization as ai_keys / sf_keys —
    # otherwise "SSA" (raw) won't find "social security administration"
    # (synonym-applied) when looking up a matched record.
    ai_annual: dict[tuple[str, str], float] = {}
    for calc in ai_calculations or []:
        # Audit-method rows ([audit] YTD cross-checks) duplicate the
        # primary calculation for the same source — never sum them in.
        if (calc.get("details") or "").startswith("[audit]"):
            continue
        amt = _money(calc.get("annualIncome"))
        if amt is not None:
            k = _income_key(calc)
            # Two records under one key are separate payments of the same
            # benefit/source (e.g. retirement + survivor Social Security)
            # — their annual total is what MuleSoft should agree with.
            ai_annual[k] = (ai_annual.get(k) or 0.0) + amt

    # SF dedup check
    sf_keys: dict[tuple, list[dict]] = {}
    for inc in sf_income:
        k = _income_key(inc)
        sf_keys.setdefault(k, []).append(inc)

    # "Zero Income" rows are declarations ("member reported no income"),
    # not income sources the AI could have missed — pull them out of
    # matching entirely. When the same member ALSO has real income rows,
    # the declaration is contradictory upstream data worth a note, not a
    # "missed income source" finding against the AI.
    members_with_real_income = {
        k[1] for k, group in sf_keys.items()
        if k[0] and k[0] != "zero income"
        and any((_money(r.get("Gross_Member_Income__c")) or 0) > 0 for r in group)
    } | {k[1] for k, amt in ai_annual.items() if amt and amt > 0}
    for k in [k for k in sf_keys if k[0] == "zero income"]:
        del sf_keys[k]
        if k[1] in members_with_real_income:
            findings.append(Finding(
                category=EXTRACTION_NOTE,
                severity="info",
                message=(
                    f"MuleSoft has a Zero Income declaration for "
                    f"'{k[1] or 'household'}' alongside actual income "
                    f"records — contradictory upstream data"
                ),
            ))

    # Detect SF duplicates within the same canonical source name. Only
    # rows with the SAME amount are duplicates — distinct amounts under
    # one key are separate payments of the same benefit (retirement +
    # survivor Social Security), which are summed at comparison time.
    for k, group in sf_keys.items():
        if len(group) > 1 and k[0]:
            amounts = {
                round(_money(r.get("Gross_Member_Income__c")) or 0.0, 2)
                for r in group
            }
            if len(amounts) > 1:
                continue
            findings.append(Finding(
                category=DUPLICATE_INCOME,
                severity="high",
                message=(
                    f"DUPLICATE INCOME — '{group[0].get('Source_Name__c')}' "
                    f"appears {len(group)} times in MuleSoft for the same member"
                ),
            ))

    ai_keys = set(_income_key(r) for r in ai_income)

    # Symmetric zero-income handling: AI-side Zero Income records (from
    # unemployment affidavits / zero-income certs) are declarations, not
    # sources MuleSoft "misses". When MuleSoft shows real income for the
    # declaring member, that contradiction IS the audit finding — a
    # member who signed an affidavit saying no income while MuleSoft
    # holds income records needs analyst verification.
    ai_zero_keys = {k for k in ai_keys if k[0] == "zero income"}
    if ai_zero_keys:
        sf_member_totals: dict[str, float] = {}
        for k, group in sf_keys.items():
            for r in group:
                amt = _money(r.get("Gross_Member_Income__c")) or 0
                if amt > 0:
                    sf_member_totals[k[1]] = sf_member_totals.get(k[1], 0) + amt
        for k in ai_zero_keys:
            ai_keys.discard(k)
            total = sf_member_totals.get(k[1])
            if total:
                findings.append(Finding(
                    category=VALUE_MISMATCH,
                    severity="medium",
                    message=(
                        f"ZERO-INCOME CONTRADICTION — "
                        f"'{(k[1] or 'household').title()}' declared zero "
                        f"income in the packet but MuleSoft shows "
                        f"${total:,.2f}/yr in income records — verify"
                    ),
                ))

    matched = ai_keys & set(sf_keys.keys())
    ai_only_keys = ai_keys - set(sf_keys.keys())
    sf_only_keys = set(sf_keys.keys()) - ai_keys

    # Amount-based matching (member-agnostic). MuleSoft's member field is
    # unreliable — it sometimes holds a funding-program label ('LIHTC', 'HUD')
    # instead of a person — so a record can fail the (source, member) key match
    # even when source + annual amount clearly agree. Pair leftover records by
    # normalized source + close annual amount, ignoring member; the member
    # difference is surfaced as a low-severity note, not a false missing/missed.
    amount_pairs: list[tuple[tuple[str, str], tuple[str, str]]] = []
    amount_matched_ai: set[tuple[str, str]] = set()
    amount_matched_sf: set[tuple[str, str]] = set()
    for ai_k in ai_only_keys:
        if not ai_k[0]:
            continue
        ai_amt = ai_annual.get(ai_k)
        if ai_amt is None or ai_amt <= 0:
            continue
        for sf_k in sf_only_keys:
            if sf_k in amount_matched_sf or not _income_sources_compatible(sf_k[0], ai_k[0]):
                continue
            sf_amt = _sf_group_amount(sf_keys[sf_k])
            # Same tolerance the exact-match income comparison uses (0.01),
            # not the asset tolerance — keep one income-amount tolerance.
            if sf_amt is not None and sf_amt > 0 and _close(ai_amt, sf_amt, tolerance=0.01):
                amount_matched_ai.add(ai_k)
                amount_matched_sf.add(sf_k)
                amount_pairs.append((ai_k, sf_k))
                break

    ai_only_keys = ai_only_keys - amount_matched_ai
    sf_only_keys = sf_only_keys - amount_matched_sf

    # Fuzzy-match remaining AI-only and SF-only sources by name similarity.
    # Catches employer name variants like:
    #   "b&t building services" (AI) vs "b&t services inc." (SF)
    #   "ABC Staffing LLC" (AI)   vs "ABC Staffing"        (SF)
    # Same threshold (0.85) as member fuzzy matching.
    fuzzy_matched_ai: set[tuple[str, str]] = set()
    fuzzy_matched_sf: set[tuple[str, str]] = set()
    fuzzy_pairs: list[tuple[tuple[str, str], tuple[str, str]]] = []

    sf_only_list = list(sf_only_keys)
    for ai_k in ai_only_keys:
        if not ai_k[0]:    # skip empty source names
            continue
        ai_normalized = _normalize_org_name(ai_k[0])
        best_ratio = 0.0
        best_sf_k: tuple[str, str] | None = None
        for sf_k in sf_only_list:
            if sf_k in fuzzy_matched_sf or not sf_k[0]:
                continue
            # Match by source name similarity AND same member (or empty member).
            # If both have member names, they must also fuzzy-match.
            if ai_k[1] and sf_k[1]:
                member_ratio = SequenceMatcher(None, ai_k[1], sf_k[1]).ratio()
                if member_ratio < 0.7:
                    continue
            sf_normalized = _normalize_org_name(sf_k[0])
            # Strip corporate suffixes/prefixes AND check per-token
            # similarity — catches "Coherent Corp" ↔ "Coherent",
            # "The Walt Disney Company" ↔ "Walt Disney Company",
            # AND "chilts" ↔ "chilis bar & grill" (per-token: chilts/chilis).
            source_ratio = _name_similarity(ai_normalized, sf_normalized)
            if source_ratio > best_ratio:
                best_ratio = source_ratio
                best_sf_k = sf_k
        if best_ratio >= 0.85 and best_sf_k is not None:
            fuzzy_matched_ai.add(ai_k)
            fuzzy_matched_sf.add(best_sf_k)
            fuzzy_pairs.append((ai_k, best_sf_k))

    # Generic-placeholder pass: MuleSoft sometimes books income under a
    # placeholder source ("Other Non Wage Source") instead of the payer's
    # name. When the income TYPE and member agree and one side's source
    # is a placeholder, it's the same income. Without this, a terminated
    # employment record — which has no amounts, so the amount pass can't
    # fire — becomes a false missing/missed CRITICAL pair.
    ai_types = {}
    for r in ai_income:
        t = r.get("incomeType")
        if t:
            ai_types.setdefault(_income_key(r), _norm(t).rstrip("s"))
    for ai_k in list(ai_only_keys - fuzzy_matched_ai):
        ai_type = ai_types.get(ai_k)
        if not ai_type:
            continue
        for sf_k in list(sf_only_keys - fuzzy_matched_sf):
            if (
                ai_k[0] not in _PLACEHOLDER_INCOME_SOURCES
                and sf_k[0] not in _PLACEHOLDER_INCOME_SOURCES
            ):
                continue
            if (
                ai_k[1] and sf_k[1] and ai_k[1] != sf_k[1]
                and _name_similarity(ai_k[1], sf_k[1]) < 0.82
            ):
                continue
            sf_type = _norm(sf_keys[sf_k][0].get("Income_Type__c")).rstrip("s")
            if sf_type and sf_type == ai_type:
                fuzzy_matched_ai.add(ai_k)
                fuzzy_matched_sf.add(sf_k)
                fuzzy_pairs.append((ai_k, sf_k))
                break

    ai_only = ai_only_keys - fuzzy_matched_ai
    sf_only = sf_only_keys - fuzzy_matched_sf

    agreements = 0
    disagreements = 0

    for k in matched:
        ai_amt = ai_annual.get(k)
        sf_amt = _sf_group_amount(sf_keys[k])
        if ai_amt is not None and sf_amt is not None and sf_amt > 0:
            if _close(ai_amt, sf_amt, tolerance=0.01):
                agreements += 1
            else:
                disagreements += 1
                findings.append(Finding(
                    category=VALUE_MISMATCH,
                    severity=_value_mismatch_severity(ai_amt, sf_amt),
                    message=(
                        f"INCOME MISMATCH — {sf_keys[k][0].get('Source_Name__c')}: "
                        f"AI ${ai_amt:,.2f} vs MuleSoft ${sf_amt:,.2f}"
                    ),
                    detail={
                        "source": sf_keys[k][0].get("Source_Name__c"),
                        "ai_amount": ai_amt,
                        "sf_amount": sf_amt,
                    },
                ))
        else:
            agreements += 1     # both present, can't compare values

    # Surface fuzzy-matched income sources. If the dollar amounts also
    # differ, escalate to INCOME MISMATCH (medium) — name variants must
    # NOT hide real discrepancies. Otherwise emit the low-severity name
    # variant note. Mirrors the asset-side pattern.
    for ai_k, sf_k in fuzzy_pairs:
        sf_rec = sf_keys[sf_k][0]
        ai_amt = ai_annual.get(ai_k)
        sf_amt = _sf_group_amount(sf_keys[sf_k])
        amount_diff = (
            ai_amt is not None and sf_amt is not None and sf_amt > 0
            and not _close(ai_amt, sf_amt, tolerance=0.01)
        )

        if amount_diff:
            disagreements += 1
            findings.append(Finding(
                category=VALUE_MISMATCH,
                severity=_value_mismatch_severity(ai_amt, sf_amt),
                message=(
                    f"INCOME MISMATCH — '{sf_rec.get('Source_Name__c')}' "
                    f"(matched to AI '{ai_k[0]}'): "
                    f"AI ${ai_amt:,.2f} vs MuleSoft ${sf_amt:,.2f}"
                ),
                detail={
                    "source": sf_rec.get("Source_Name__c"),
                    "ai_source": ai_k[0],
                    "ai_amount": ai_amt,
                    "sf_amount": sf_amt,
                },
            ))
        else:
            agreements += 1
            findings.append(Finding(
                category=VALUE_MISMATCH,
                severity="low",
                message=(
                    f"Income source name variant — AI: '{ai_k[0]}' vs "
                    f"MuleSoft: '{sf_k[0]}' (likely same source)"
                ),
            ))

    # Amount-matched pairs are agreements by construction (same source, close
    # annual amount). Surface the member difference so the analyst can see when
    # MuleSoft's member field is wrong (e.g. 'LIHTC'/'HUD' instead of a person).
    for ai_k, sf_k in amount_pairs:
        agreements += 1
        ai_member = ai_k[1]
        sf_member = sf_k[1]
        if ai_member and sf_member and ai_member != sf_member:
            findings.append(Finding(
                category=VALUE_MISMATCH,
                severity="low",
                message=(
                    f"Income member differs — '{ai_k[0]}': AI member "
                    f"'{ai_member}' vs MuleSoft '{sf_member}' "
                    f"(matched by source + amount)"
                ),
            ))
        if ai_k[0] != sf_k[0]:
            findings.append(Finding(
                category=VALUE_MISMATCH,
                severity="low",
                message=(
                    f"Income program variant — AI '{ai_k[0]}' vs MuleSoft "
                    f"'{sf_k[0]}' (same SSA-family benefit matched by amount)"
                ),
            ))

    # AI-only — drop empty source names (useless finding "MuleSoft missing ''")
    ai_only_clean = {k for k in ai_only if k[0]}
    for k in ai_only_clean:
        findings.append(Finding(
            category=MISSING_INCOME,
            severity="high",
            message=f"MuleSoft missing income source — '{k[0]}' for {k[1] or 'household'}",
        ))

    # SF-only — cluster variant spellings ('walmart' / 'wal-mart' / 'walmart inc')
    # so MuleSoft's same-source-many-rows shows as one finding, not many.
    sf_only_clusters = _cluster_income_keys(sf_only)
    for cluster in sf_only_clusters:
        rep = cluster[0]
        member = rep[1] or "household"
        if ir_scoped:
            sev = "info"
            msg = (
                f"Income source '{rep[0]}' for {member} is in MuleSoft's "
                f"full-case record, not the interim packet — verify if changed (IR)"
            )
        elif len(cluster) > 1:
            sev = "medium"
            variants = ", ".join(f"'{k[0]}'" for k in cluster[:3])
            if len(cluster) > 3:
                variants += f", +{len(cluster) - 3} more"
            msg = (
                f"AI may have missed income source — '{rep[0]}' for {member} "
                f"(MuleSoft has {len(cluster)} variant spellings: {variants})"
            )
        else:
            sev = "medium"
            msg = f"AI may have missed income source — '{rep[0]}' for {member}"
        findings.append(Finding(
            category=IDP_MISSED_INCOME,
            severity=sev,
            message=msg,
        ))

    return findings, {
        "agreements": agreements,
        "disagreements": disagreements,
        "ai_only": len(ai_only_clean),
        "sf_only": len(sf_only_clusters),
    }


# ---------------------------------------------------------------------------
# Asset comparison
# ---------------------------------------------------------------------------

# MuleSoft stores an asset's balance/value across several fields depending on
# how it was verified (VOA, bank statement, self-declaration, real estate).
# Reading only Cash_Value__c/VOA_Current__c silently drops assets whose balance
# lives elsewhere — they look like null-balance orphans and get filtered out
# before comparison. Read all of them, most-canonical first.
_SF_ASSET_BALANCE_FIELDS = (
    "Cash_Value__c",
    "VOA_Current__c",
    "VOA_Cash_Value__c",
    "Asset_Cash_Value__c",
    "Recent_Bank_Statement_Balance__c",
    "Self_Declared_Balance__c",
    "VOA_Net_Value__c",
    "Net_Value_of_Real_Estate__c",
    "Current_Market_Value__c",
)


def _sf_asset_balance(rec: dict) -> float | None:
    """Balance/value across MuleSoft's asset balance fields.

    First NON-ZERO value wins; 0.0 is returned only when every populated
    field is zero. MuleSoft rows routinely carry 0.0 in higher-priority
    fields (Cash_Value__c = 0.0) while the real balance sits further down
    (Asset_Cash_Value__c = 1600.0) — treating zero as "populated" masks
    the real balance and makes the record unmatchable by amount.
    """
    zero_seen = False
    for f in _SF_ASSET_BALANCE_FIELDS:
        val = _money(rec.get(f))
        if val is None:
            continue
        if val != 0:
            return val
        zero_seen = True
    return 0.0 if zero_seen else None


def _ai_asset_balance(rec: dict) -> float | None:
    """First populated balance on an AI asset record.

    Verified balance first, self-declared as fallback (mirrors
    _sf_asset_balance, including its zero-skipping). Asset
    self-certifications put the amount in selfDeclaredAmount — every
    consumer (matching, comparison, findings) must read the same fields
    or a record becomes unmatchable by the tier scorer while the
    findings renderer still shows its amount.
    """
    zero_seen = False
    for f in ("currentBalance", "selfDeclaredAmount"):
        val = _money(rec.get(f))
        if val is None:
            continue
        if val != 0:
            return val
        zero_seen = True
    return 0.0 if zero_seen else None


def _asset_key(rec: dict) -> tuple[str, str, str]:
    """sourceName + accountType + last 4 of accountNumber."""
    src = _norm(rec.get("sourceName") or rec.get("Source_Name__c"))
    acct_type = _norm(rec.get("accountType") or rec.get("Account_Type__c"))
    acct_num = str(rec.get("accountNumber") or "").strip()
    if not acct_num:
        # Fall back to a balance-based stub for SF records without account #.
        # Keep the stub whole — last-4 truncation would strip the '~' marker
        # (breaking every startswith("~") stub check downstream) and collide
        # distinct accounts whose balances share trailing digits.
        bal = _sf_asset_balance(rec)
        if bal is None:
            bal = _ai_asset_balance(rec)
        stub = f"~{bal}" if bal is not None else "~"
        return (src, acct_type, stub.lower())
    last4 = acct_num[-4:].lower() if len(acct_num) >= 4 else acct_num.lower()
    return (src, acct_type, last4)


def _compare_assets(
    ai_assets: list[dict], sf_assets: list[dict], *, ir_scoped: bool = False,
) -> tuple[list[Finding], dict]:
    findings: list[Finding] = []

    # Filter out SF asset records with no identifying fields — they're
    # placeholder rows MuleSoft sometimes creates that we can't compare
    # meaningfully. (Examples: real-estate stubs with no source/account.)
    sf_assets_filtered: list[dict] = []
    sf_orphan_count = 0
    for a in sf_assets:
        has_source = bool((a.get("Source_Name__c") or "").strip())
        has_account = bool((a.get("accountNumber") or "").strip())
        has_balance = _sf_asset_balance(a)
        if not has_source and not has_account and not has_balance:
            sf_orphan_count += 1
            continue
        sf_assets_filtered.append(a)

    if sf_orphan_count > 0:
        logger.debug(
            "Filtered %d MuleSoft asset record(s) with no identifying fields",
            sf_orphan_count,
        )

    sf_keys: dict[tuple, list[dict]] = {}
    for a in sf_assets_filtered:
        k = _asset_key(a)
        sf_keys.setdefault(k, []).append(a)

    for k, group in sf_keys.items():
        if len(group) > 1:
            findings.append(Finding(
                category=DUPLICATE_ASSET,
                severity="high",
                message=(
                    f"DUPLICATE ASSET — '{group[0].get('Source_Name__c')}' "
                    f"({group[0].get('Account_Type__c')}) appears {len(group)} times"
                ),
            ))

    ai_keys = {_asset_key(a): a for a in ai_assets}
    matched = ai_keys.keys() & set(sf_keys.keys())
    ai_only_keys = ai_keys.keys() - set(sf_keys.keys())
    sf_only_keys = set(sf_keys.keys()) - ai_keys.keys()

    # Fuzzy-match remaining assets by sourceName similarity + same accountType
    # + close balance. Catches variants like:
    #   "Knights Of Columbus" (AI) vs "4633 KOC" (MuleSoft)
    #   "The Walt Disney Company" (AI) vs "Walt Disney Company" (MuleSoft)
    fuzzy_matched_ai_assets: set[tuple] = set()
    fuzzy_matched_sf_assets: set[tuple] = set()
    asset_fuzzy_pairs: list[tuple[tuple, tuple]] = []

    # Score EVERY candidate (ai, sf) pair, then assign globally best-first
    # (one-to-one). A per-record greedy match mis-pairs when several accounts
    # share a bank name: e.g. two Checking accounts at the same bank, only one
    # of which matches MuleSoft's balance — greedy could claim MuleSoft's
    # record for the WRONG account, leaving the true match flagged "MuleSoft
    # missing" and inventing a balance mismatch. Scoring ranks balance-matching
    # pairs ABOVE name-only pairs so the balance-correct pairing always wins;
    # same-name/different-balance is a last resort, taken only if nothing
    # better claims that record (then it surfaces as a real balance mismatch).
    sf_only_list = list(sf_only_keys)
    candidates: list[tuple[float, tuple, tuple]] = []
    for ai_k in ai_only_keys:
        ai_rec = ai_keys[ai_k]
        ai_src_norm = _normalize_org_name(ai_k[0])
        ai_type = ai_k[1]
        ai_bal = _ai_asset_balance(ai_rec)
        if not ai_src_norm and ai_bal is None:
            continue   # nothing to match on
        for sf_k in sf_only_list:
            sf_rec = sf_keys[sf_k][0]
            sf_src_norm = _normalize_org_name(sf_k[0])
            sf_bal = _sf_asset_balance(sf_rec)
            type_ok = _account_types_compatible(ai_type, sf_k[1])
            name_score = (
                _name_similarity(ai_src_norm, sf_src_norm)
                if (ai_src_norm and sf_src_norm) else 0.0
            )
            names_ok = name_score >= 0.85 or not ai_src_norm or not sf_src_norm
            balance_match = (
                ai_bal is not None and sf_bal is not None
                and _close(ai_bal, sf_bal, tolerance=0.02)
            )
            balance_conflict = (
                ai_bal is not None and sf_bal is not None and not balance_match
            )

            # Tiered score — higher tier wins regardless of name nuance:
            if balance_match and type_ok and names_ok:
                score = 3.0 + name_score            # balances agree — most reliable
            elif name_score >= 0.95 and not balance_conflict:
                score = 2.0 + name_score            # near-perfect name, no contradiction
            elif name_score >= 0.85 and type_ok and not balance_conflict:
                score = 1.0 + name_score            # moderate name, no contradiction
            elif name_score >= 0.95 and balance_conflict:
                score = name_score                  # same name, diff balance — last resort
            else:
                continue
            candidates.append((score, ai_k, sf_k))

    candidates.sort(key=lambda c: c[0], reverse=True)
    for _score, ai_k, sf_k in candidates:
        if ai_k in fuzzy_matched_ai_assets or sf_k in fuzzy_matched_sf_assets:
            continue
        fuzzy_matched_ai_assets.add(ai_k)
        fuzzy_matched_sf_assets.add(sf_k)
        asset_fuzzy_pairs.append((ai_k, sf_k))

    ai_only = ai_only_keys - fuzzy_matched_ai_assets
    sf_only = sf_only_keys - fuzzy_matched_sf_assets

    agreements = 0
    disagreements = 0

    for k in matched:
        ai_bal = _ai_asset_balance(ai_keys[k])
        sf_bal = _sf_asset_balance(sf_keys[k][0])
        if ai_bal is not None and sf_bal is not None:
            if _close(ai_bal, sf_bal, tolerance=0.02):
                agreements += 1
            else:
                disagreements += 1
                findings.append(Finding(
                    category=VALUE_MISMATCH,
                    severity=_value_mismatch_severity(ai_bal, sf_bal),
                    message=(
                        f"ASSET BALANCE MISMATCH — "
                        f"{sf_keys[k][0].get('Source_Name__c')} "
                        f"{sf_keys[k][0].get('Account_Type__c')}: "
                        f"AI ${ai_bal:,.2f} vs MuleSoft ${sf_bal:,.2f}"
                    ),
                ))
        else:
            agreements += 1

    # Surface fuzzy-matched assets as low-severity name variants.
    # Treat as agreements for confidence scoring. Also flag if the
    # balances differ between systems — that's a real discrepancy
    # the analyst should see.
    for ai_k, sf_k in asset_fuzzy_pairs:
        agreements += 1
        ai_rec = ai_keys[ai_k]
        sf_rec = sf_keys[sf_k][0]
        ai_src = ai_rec.get("sourceName") or "(unnamed)"
        sf_src = sf_rec.get("Source_Name__c") or "(unnamed)"
        ai_bal = _ai_asset_balance(ai_rec)
        sf_bal = _sf_asset_balance(sf_rec)

        # Determine the right phrasing
        if ai_src.lower() != sf_src.lower():
            name_msg = (
                f"Asset name variant — AI: '{ai_src}' vs "
                f"MuleSoft: '{sf_src}' (likely same asset)"
            )
        else:
            name_msg = None  # only case differs — don't bother flagging

        balance_diff = (
            ai_bal is not None and sf_bal is not None
            and not _close(ai_bal, sf_bal, tolerance=0.02)
        )

        if balance_diff:
            findings.append(Finding(
                category=VALUE_MISMATCH,
                severity=_value_mismatch_severity(ai_bal, sf_bal),
                message=(
                    f"ASSET BALANCE MISMATCH — '{sf_src}' "
                    f"({sf_rec.get('Account_Type__c') or ai_rec.get('accountType')}): "
                    f"AI ${ai_bal:,.2f} vs MuleSoft ${sf_bal:,.2f}"
                ),
            ))
        elif name_msg:
            findings.append(Finding(
                category=VALUE_MISMATCH,
                severity="low",
                message=name_msg,
            ))

    # AI-only — drop entries with no identifying name (useless finding)
    ai_only_clean = {k for k in ai_only if (k[0] or k[2])}
    for k in ai_only_clean:
        rec = ai_keys[k]
        bal = _ai_asset_balance(rec)
        # A zero-value asset carries nothing material — surface as a NOTE, not
        # a CRITICAL, so an empty placeholder (e.g. 'Self-Declared Cash $0.00')
        # doesn't head the analyst's critical list. Unknown balance (None) is
        # kept as high — it might be material, we just couldn't read it.
        severity = "info" if bal == 0 else "high"
        findings.append(Finding(
            category=MISSING_ASSET,
            severity=severity,
            message=(
                f"MuleSoft missing asset — '{rec.get('sourceName')}' "
                f"({rec.get('accountType')}) ${bal or 0:,.2f}"
            ),
        ))

    # SF-only — cluster keys that look like the same real account under
    # different name variants (e.g. 'BOA - Checking 2390' / 'BOA CK# 2390').
    sf_only_clusters = _cluster_asset_keys(sf_only)
    for cluster in sf_only_clusters:
        rep_key = cluster[0]
        rep_rec = sf_keys[rep_key][0]
        rep_bal = _sf_asset_balance(rep_rec)
        if ir_scoped:
            severity = "info"
            msg = (
                f"Asset '{rep_rec.get('Source_Name__c')}' is in MuleSoft's "
                f"full-case record, not the interim packet — verify if changed (IR)"
            )
        elif len(cluster) > 1:
            severity = "medium"
            variants = ", ".join(
                f"'{sf_keys[k][0].get('Source_Name__c')}'" for k in cluster[:3]
            )
            if len(cluster) > 3:
                variants += f", +{len(cluster) - 3} more"
            msg = (
                f"AI may have missed asset — '{rep_rec.get('Source_Name__c')}' "
                f"is in MuleSoft ({len(cluster)} variant spellings: {variants})"
            )
        else:
            # Single zero-value MuleSoft asset is immaterial — NOTE, not REVIEW.
            severity = "info" if rep_bal == 0 else "medium"
            msg = (
                f"AI may have missed asset — '{rep_rec.get('Source_Name__c')}' "
                f"is in MuleSoft"
            )
        findings.append(Finding(
            category=IDP_MISSED_ASSET,
            severity=severity,
            message=msg,
        ))

    return findings, {
        "agreements": agreements,
        "disagreements": disagreements,
        "ai_only": len(ai_only_clean),
        "sf_only": len(sf_only_clusters),
    }


# ---------------------------------------------------------------------------
# Certification-level scalar comparison
# ---------------------------------------------------------------------------

def _norm_unit(v: Any) -> str:
    """Normalize a unit number so building/floor prefixes don't cause false
    mismatches: '1 501' → '501', 'Bldg 2 Unit 27' → '27', '#27' → '27'.

    Takes the last alphanumeric token, which is the unit itself.
    """
    raw = _norm(v)
    if not raw:
        return ""
    tokens = [t for t in re.split(r"[\s\-#/]+", raw) if t]
    return tokens[-1] if tokens else raw


# Document types that count as THE certification form. "(Previous)"
# variants are excluded — a packet containing only the prior year's cert
# has no current cert to compare.
_CERT_FORM_MARKERS = ("50059", "tenant income certification", "(tic)", "3560")


def _cert_form_present(extraction: dict) -> bool:
    """True when the packet contains a current certification form group."""
    for g in extraction.get("document_groups") or []:
        if not isinstance(g, dict):
            continue
        dt = str(g.get("document_type") or "").lower()
        if g.get("category") == "ignore" or "(previous)" in dt:
            continue
        if any(m in dt for m in _CERT_FORM_MARKERS):
            return True
    return False


def _compare_certification(
    ai_cert: dict, sf_review: dict | None,
) -> tuple[list[Finding], dict]:
    """Cross-check certification-level scalar fields between IDP and MuleSoft.

    These fields (effective date, cert type, unit, income total, rent) are
    never record-matched by the other _compare_* functions. Without this check
    a field that disagrees between the two systems is simply invisible — which
    is how a cert with a year-off effective date can score a false GREEN. Each
    compared field counts toward agreement/disagreement so a real mismatch
    actually moves the confidence needle, not just appends a finding.

    Only fields present on BOTH sides are scored (one-sided fields aren't a
    cross-system disagreement). Numeric fields use tolerance; the unit number
    is prefix-normalized; rent is reconciled the LIHTC way (see below).
    """
    findings: list[Finding] = []
    agreements = 0
    disagreements = 0

    if not ai_cert or not sf_review:
        return findings, {"agreements": 0, "disagreements": 0, "ai_only": 0, "sf_only": 0}

    def _emit(ok: bool, finding: Finding | None) -> None:
        nonlocal agreements, disagreements
        if ok:
            agreements += 1
        elif finding is not None:
            disagreements += 1
            findings.append(finding)

    # --- Effective date (date-only, exact) ---
    ai_eff = str(ai_cert.get("effectiveDate") or "")[:10]
    sf_eff = str(sf_review.get("Effective_Date__c") or "")[:10]
    if ai_eff and sf_eff:
        _emit(ai_eff == sf_eff, Finding(
            category=VALUE_MISMATCH, severity="high",
            message=f"EFFECTIVE DATE MISMATCH — AI {ai_eff} vs MuleSoft {sf_eff}",
            detail={"field": "effectiveDate", "ai": ai_eff, "sf": sf_eff},
        ))

    # --- Certification type (case-insensitive, exact) ---
    ai_ct = _norm(ai_cert.get("certificationType"))
    sf_ct = _norm(sf_review.get("Certification_Type__c"))
    if ai_ct and sf_ct:
        _emit(ai_ct == sf_ct, Finding(
            category=VALUE_MISMATCH, severity="medium",
            message=f"CERT TYPE MISMATCH — AI '{ai_ct.upper()}' vs MuleSoft '{sf_ct.upper()}'",
        ))

    # --- Unit number (prefix-normalized) ---
    ai_unit = _norm_unit(ai_cert.get("unitNumber"))
    sf_unit = _norm_unit(sf_review.get("Unit_Number__c"))
    if ai_unit and sf_unit:
        _emit(ai_unit == sf_unit, Finding(
            category=VALUE_MISMATCH, severity="low",
            message=(f"UNIT NUMBER MISMATCH — AI '{ai_cert.get('unitNumber')}' "
                     f"vs MuleSoft '{sf_review.get('Unit_Number__c')}'"),
        ))

    # --- Household income total (numeric, 5% tolerance) ---
    # Catches MuleSoft over/under-count (e.g. a duplicated income source
    # inflating Total_Income__c above the TIC-declared household income).
    ai_inc = _money(ai_cert.get("householdIncome"))
    sf_inc = _money(sf_review.get("Total_Income__c")
                    or sf_review.get("Total_Gross_Household_Income__c"))
    if ai_inc is not None and sf_inc is not None and (ai_inc > 0 or sf_inc > 0):
        _emit(_close(ai_inc, sf_inc, tolerance=0.05), Finding(
            category=VALUE_MISMATCH,
            severity=_value_mismatch_severity(ai_inc, sf_inc),
            message=(f"HOUSEHOLD INCOME MISMATCH — AI ${ai_inc:,.2f} "
                     f"vs MuleSoft ${sf_inc:,.2f}"),
            detail={"field": "householdIncome", "ai": ai_inc, "sf": sf_inc},
        ))

    # --- Household size (integer) ---
    ai_sz = _money(ai_cert.get("householdSize"))
    sf_sz = _money(sf_review.get("Number_Members__c"))
    if ai_sz is not None and sf_sz is not None:
        _emit(int(ai_sz) == int(sf_sz), Finding(
            category=VALUE_MISMATCH, severity="medium",
            message=f"HOUSEHOLD SIZE MISMATCH — AI {int(ai_sz)} vs MuleSoft {int(sf_sz)}",
        ))

    # --- Rent reconciliation (LIHTC: gross rent = tenant rent + utility allowance) ---
    # MuleSoft 'Gross_Rent__c' is the LIHTC gross (tenant + UA), so reconcile it
    # against IDP's tenantRent + utilityAllowance — NOT IDP's grossRent field,
    # which is often the contract/market rent (a different concept that would
    # false-flag).
    sf_gross = _money(sf_review.get("Gross_Rent__c"))
    ai_gross = _money(ai_cert.get("grossRent"))
    ai_tenant = _money(ai_cert.get("tenantRent"))
    ai_ua = _money(ai_cert.get("utilityAllowance"))
    if sf_gross is not None and sf_gross > 0:
        if ai_gross is not None and ai_gross > 0:
            # Compare the form's own gross rent directly when extracted.
            # Reconstructing gross as tenant+UA is only valid for LIHTC
            # (tenant pays the full rent); on HUD S8 gross = contract rent
            # + UA while the tenant pays an income-based share, so the
            # reconstruction manufactures a mismatch (tenant $469 + UA $11
            # = $480 "vs" $2,300) even when both systems agree on $2,300.
            _emit(_close(ai_gross, sf_gross, tolerance=0.02), Finding(
                category=VALUE_MISMATCH,
                severity=_value_mismatch_severity(ai_gross, sf_gross),
                message=(f"GROSS RENT MISMATCH — AI ${ai_gross:,.2f} "
                         f"vs MuleSoft ${sf_gross:,.2f}"),
            ))
        elif ai_tenant is not None and ai_ua is not None:
            # Fallback reconstruction — only meaningful where tenant rent
            # approximates gross (LIHTC-style, no rental assistance).
            ai_gross_equiv = ai_tenant + ai_ua
            _emit(_close(ai_gross_equiv, sf_gross, tolerance=0.02), Finding(
                category=VALUE_MISMATCH,
                severity=_value_mismatch_severity(ai_gross_equiv, sf_gross),
                message=(f"GROSS RENT MISMATCH — AI ${ai_gross_equiv:,.2f} "
                         f"(tenant ${ai_tenant:,.2f} + utility ${ai_ua:,.2f}) "
                         f"vs MuleSoft ${sf_gross:,.2f}"),
            ))

    return findings, {
        "agreements": agreements,
        "disagreements": disagreements,
        "ai_only": 0,
        "sf_only": 0,
    }


# ---------------------------------------------------------------------------
# Compliance findings (IDP-internal — no MuleSoft comparison needed)
# ---------------------------------------------------------------------------

def _classify_idp_finding(msg: str) -> tuple[str, str]:
    """Categorize and assign severity to a raw IDP finding string.

    The IDP pipeline produces strings in a few patterns:
      "[RED] X → field: Not extracted"          → field quality, high
      "[YELLOW] X → field: Not found ..."       → field quality, medium
      "Income discrepancy ... 92% difference"   → internal mismatch, medium
      "Income total mismatch: ..."              → internal mismatch, medium
      "... must be signed (Section 11)"         → compliance, high
      "Missing required compliance document"    → compliance, high
      "Pages 7: ... excluded"                   → extraction note, info
      "Name variants detected ..."              → extraction note, info
    Returns (category, severity).
    """
    lowered = msg.lower()

    if msg.startswith("[RED]"):
        return (FIELD_QUALITY, "high")
    if msg.startswith("[YELLOW]"):
        return (FIELD_QUALITY, "medium")

    if "discrepancy" in lowered or "mismatch" in lowered:
        return (INTERNAL_DISCREPANCY, "medium")

    if (
        "must be signed" in lowered
        or "missing required" in lowered
        or "resubmission required" in lowered
        or "certification requires" in lowered
        or "0 signed of" in lowered
    ):
        return (COMPLIANCE, "high")

    if "review" in lowered or "verify" in lowered:
        return (COMPLIANCE, "medium")

    if "excluded" in lowered or "name variants detected" in lowered:
        return (EXTRACTION_NOTE, "info")

    if "homeless" in lowered or "overpayment" in lowered:
        return (COMPLIANCE, "high")

    return (EXTRACTION_NOTE, "low")


def _idp_internal_findings(extraction: dict) -> list[Finding]:
    """Pull all findings produced by the IDP pipeline itself.

    Includes compliance, cross-doc validation, special scenarios, bug
    detection, cert type rules, and field-level scoring — basically
    everything the IDP pipeline writes into `extraction.findings`.

    These are NOT comparison findings (those come from _compare_*).
    """
    findings: list[Finding] = []
    seen_messages: set[str] = set()

    raw_findings = extraction.get("findings") or []
    for msg in raw_findings:
        if not msg or not isinstance(msg, str):
            continue
        msg_clean = msg.strip()
        if not msg_clean:
            continue
        # Dedup identical strings
        if msg_clean in seen_messages:
            continue
        seen_messages.add(msg_clean)

        category, severity = _classify_idp_finding(msg_clean)
        findings.append(Finding(
            category=category,
            severity=severity,
            message=msg_clean,
        ))

    # Belt-and-suspenders: also flag unsigned TIC if the IDP findings
    # list didn't include it but the cert_info says isSigned=No. Only
    # when a cert form actually exists — otherwise the real problem is
    # the missing form, which has its own finding.
    cert = extraction.get("certification_info") or {}
    if str(cert.get("isSigned") or "").lower() == "no" and _cert_form_present(extraction):
        unsigned_msg = "UNSIGNED TIC — TIC form not signed. Resubmission required."
        if unsigned_msg not in seen_messages and not any(
            "not signed" in f.message.lower() for f in findings
        ):
            findings.append(Finding(
                category=COMPLIANCE,
                severity="high",
                message=unsigned_msg,
            ))

    return findings


# ---------------------------------------------------------------------------
# Confidence score
# ---------------------------------------------------------------------------

# Minimum extraction score for an IR to be treated as a legitimately-scoped
# packet (rather than a failed extraction). Below this, MuleSoft-only records
# are penalized normally so genuine failures stay RED.
# POLICY default, not sample-derived — this is the value most worth calibrating
# against the real distribution of IR extraction scores once volume exists.
_IR_HEALTHY_EXTRACTION = 0.6


def _calculate_confidence(
    extraction: dict,
    member_stats: dict, income_stats: dict, asset_stats: dict,
    cert_stats: dict,
    comparison_findings: list[Finding],
    ir_scoped: bool = False,
) -> Confidence:
    field_scores = extraction.get("field_scores") or {}
    extraction_score = float(field_scores.get("overall_composite") or 0.0)

    agreements = (member_stats["agreements"] + income_stats["agreements"]
                  + asset_stats["agreements"] + cert_stats["agreements"])
    disagreements = (member_stats["disagreements"] + income_stats["disagreements"]
                     + asset_stats["disagreements"] + cert_stats["disagreements"])
    ai_only = (member_stats["ai_only"] + income_stats["ai_only"]
               + asset_stats["ai_only"] + cert_stats["ai_only"])
    sf_only = (member_stats["sf_only"] + income_stats["sf_only"]
               + asset_stats["sf_only"] + cert_stats["sf_only"])

    if ir_scoped:
        # Scoped IR (gated on healthy extraction in compare()): MuleSoft-only
        # records reflect the full case, not an IDP miss, so exclude them from
        # the rate entirely — neither penalty nor weight.
        weight = agreements + disagreements
        if weight > 0:
            agreement_rate = max(0.0, min(1.0, agreements / weight))
        else:
            agreement_rate = 1.0 if (agreements or ai_only) else 0.5
    else:
        # Don't penalize "AI catches MuleSoft miss"; do penalize disagreements
        # and "AI missed something MuleSoft has".
        weight = agreements + disagreements + (sf_only * 0.5)
        if weight > 0:
            rate = (agreements - 0.5 * sf_only) / weight
            agreement_rate = max(0.0, min(1.0, rate))
        else:
            # No comparable records (MuleSoft has nothing) — confidence
            # rests on extraction quality alone.
            agreement_rate = 1.0 if ai_only > 0 else 0.5

    case_confidence = (extraction_score * 0.6) + (agreement_rate * 0.4)
    flag = ("green" if case_confidence >= 0.85
            else "yellow" if case_confidence >= 0.65
            else "red")

    # Severity cap: a single high-severity cross-system disagreement (e.g. a
    # year-off effective date, a duplicated income source, a member MuleSoft is
    # missing) must never read GREEN, even when the averaged score is high. The
    # average washes out lone-but-critical mismatches, which is exactly how a
    # bad cert slips through as green. Only COMPARISON findings cap the flag —
    # IDP-internal compliance/field-quality findings are scored separately.
    if flag == "green" and any(f.severity == "high" for f in comparison_findings):
        flag = "yellow"

    return Confidence(
        extraction_score=extraction_score,
        agreement_rate=agreement_rate,
        case_confidence=case_confidence,
        flag=flag,
        agreements=agreements,
        disagreements=disagreements,
        ai_only_records=ai_only,
        sf_only_records=sf_only,
    )


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def compare(extraction: dict, sf_data: dict) -> ComparisonResult:
    """Diff IDP extraction against MuleSoft data; return findings + score."""
    ai_members = (extraction.get("household_demographics") or {}).get("houseHold") or []
    ai_income = ((extraction.get("income") or {}).get("sourceIncome") or {}).get("verificationIncome") or []
    ai_calculations = extraction.get("income_calculations") or []
    ai_assets = (extraction.get("assets") or {}).get("assetInformation") or []
    ai_cert = extraction.get("certification_info") or {}

    sf_members = sf_data.get("members") or []
    sf_income = sf_data.get("income") or []
    sf_assets = sf_data.get("assets") or []
    sf_review = sf_data.get("review")

    # Interim Recertification packets are scoped to the change that triggered
    # them, so MuleSoft holding more records than IDP is EXPECTED — not an IDP
    # miss. But only treat it that way when the extraction is healthy: a low
    # extraction score means IDP failed outright (not scoping), so it must
    # still be penalized normally. This single flag drives both the reframed
    # MuleSoft-only messages and the confidence down-weight.
    extraction_score = float(
        (extraction.get("field_scores") or {}).get("overall_composite") or 0.0
    )
    cert_type = (
        ai_cert.get("certificationType")
        or (sf_review or {}).get("Certification_Type__c")
        or ""
    )
    ir_scoped = (
        str(cert_type).upper() == "IR"
        and extraction_score >= _IR_HEALTHY_EXTRACTION
    )

    member_findings, member_stats = _compare_members(
        ai_members, sf_members, ir_scoped=ir_scoped)
    income_findings, income_stats = _compare_income(
        ai_income, ai_calculations, sf_income, ir_scoped=ir_scoped)
    asset_findings, asset_stats = _compare_assets(
        ai_assets, sf_assets, ir_scoped=ir_scoped)
    cert_findings, cert_stats = _compare_certification(ai_cert, sf_review)
    if not _cert_form_present(extraction):
        # The AI's cert scalars were harvested from secondary documents
        # (EIV report, correspondence) — e.g. an EIV references the LAST
        # completed cert, so its effective date legitimately differs from
        # the new cert MuleSoft holds. Comparing them as if cert-vs-cert
        # produces false CRITICALs and craters the agreement rate, so the
        # comparison becomes advisory: findings drop to NOTES and none of
        # it counts toward agreement/disagreement.
        for f in cert_findings:
            if f.severity in ("high", "medium"):
                f.severity = "low"
                f.message += (
                    " (advisory — no certification form in packet; AI value "
                    "comes from secondary documents)"
                )
        cert_stats = {
            "agreements": 0, "disagreements": 0, "ai_only": 0, "sf_only": 0,
        }
    idp_findings = _idp_internal_findings(extraction)

    comparison_findings = (
        member_findings + income_findings + asset_findings + cert_findings
    )

    # IR packets deliberately contain only the change documents. When low
    # extraction quality disables ir_scoped mode, the comparison runs
    # against MuleSoft's FULL case record — everything not in the interim
    # packet then surfaces as "AI may have missed X". Those are expected
    # absences, not audit signal; keep them visible but out of the
    # analyst's action buckets. (AI-only findings keep their severity:
    # something in the packet that MuleSoft lacks IS change-related.)
    if str(cert_type).upper() == "IR" and not ir_scoped:
        for f in comparison_findings:
            if (
                f.category in (IDP_MISSED_MEMBER, IDP_MISSED_INCOME, IDP_MISSED_ASSET)
                and f.severity in ("high", "medium")
            ):
                f.severity = "low"
                f.message += (
                    " (interim packet compared against full case record — "
                    "verify only if related to the interim change)"
                )

    findings = comparison_findings + idp_findings
    confidence = _calculate_confidence(
        extraction, member_stats, income_stats, asset_stats, cert_stats,
        comparison_findings, ir_scoped=ir_scoped,
    )

    return ComparisonResult(findings=findings, confidence=confidence)
